---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: spring-music-repo
outputs:
  - name: binaries

run:
  path: spring-music-repo/ci/tasks/build-artifact.sh
