---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: spring-music-repo

run:
  path: sh
  args:
  - -exc
  - |
    curl -L -o gradle.zip "https://services.gradle.org/distributions/gradle-3.5-bin.zip"
    unzip gradle.zip
    cd spring-music-repo && ../gradle-3.5/bin/gradle test
